# 1. Service Identification
spring.application.name=comment-service
server.port=8083

# 2. Database Configuration (MySQL)
# Make sure you have created 'inkwell_comment' database in MySQL
spring.datasource.url=${SPRING_DATABASE_URL:jdbc:mysql://localhost:3306/inkwell_comment?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATABASE_USERNAME:root}
spring.datasource.password=${SPRING_DATABASE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 4. Eureka Discovery Client Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# 5. Optional: Logging (For Debugging)
logging.level.org.springframework.security=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.rabbitmq.listener.simple.default-requeue-rejected=false




