server.port=8080
spring.application.name=api-gateway

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 1. Route to Auth-Service (NO FILTER HERE)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# 2. Route to Post-Service (FILTER ADDED HERE)
spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://POST-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/posts/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter