# Server Port
server.port=8082
spring.application.name=post-service

# Database Configuration (Separate DB for each service is Microservices best practice)
spring.datasource.url=${SPRING_DATABASE_URL:jdbc:mysql://localhost:3306/inkwell_post?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATABASE_USERNAME:root}
spring.datasource.password=${SPRING_DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

# Eureka Discovery Client - To register this service in the phonebook
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest