server.port=9090
spring.application.name=website-controller

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false